import React from "react";

const Testimonial = props => {
  return (
    <div className={props.className}>
      <div className="d-block w-100 text-center">
        <img
          className="img-fluid"
          src={require(`../../media/AI-generated/${props.AIphoto}`)}
          alt="testimonial" style={{width:"5em", height:"5em"}}
        />
        <h4 className="mt-3">{("Best Organic Store Ever").toUpperCase()}</h4>
        <p>{props.content}</p>
        <p>{props.author}</p>
        <p>Generated by Testimonial Generator</p>
      </div>
    </div>
  );
};
export default Testimonial;
